Hello Microverse Project Pull Request
Ewoskyx/Hello-Microverse-Project pull request #1
Opened 2021-10-19 13:45 UTC by Ewoskyx

Changes are done on the following file(s) as suggested by the reviewer.

-  README.md (Getting started and Live demo explanations are updated)

2021-10-19 16:32 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Evren Ersoy, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
GitHub flow is followed. :heavy_check_mark:
## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-19 16:32 UTC, SajjadAhmad14 commented on README.md
> -[Live Demo Link](https://livedemo.com)
Please remove the Live demo as it does not have an active link.

2021-10-19 16:32 UTC, SajjadAhmad14 commented on README.md
> -## Getting Started
Please add instructions to run the project locally for non-technical people.

2021-10-19 16:32 UTC, SajjadAhmad14 commented on index.html
> +<!DOCTYPE html>
PR should have a descriptive title and summary.

2021-10-20 09:08 UTC, dasileker requested changes
### **Hi @Ewoskyx,** 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._
- Like the previous TSE mentioned that the **PR** should be descriptive.

![mmmmm](https://user-images.githubusercontent.com/61562626/138063726-66fa5db7-b3b1-4ce0-a28c-621bd939366e.jpeg)
![pppp](https://user-images.githubusercontent.com/61562626/138063736-0de59f1b-8336-443c-a2d3-2d7e53bdd55b.jpeg)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-20 09:29 UTC, ZeenatLawal approved these changes
Hi @Ewoskyx, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

## Congratulations! 🎉 
![6vEo](https://user-images.githubusercontent.com/46851023/133564373-95c66227-e33a-4506-b21a-d6db9b3a2050.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-10-20 09:35 UTC, merged